import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/common/Header";
import QueryProvider from "@/provider/QueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="min-h-screen flex flex-col">
        <QueryProvider>
          <Header />
          <main className="flex justify-center">{children}</main>
        </QueryProvider>
      </body>
    </html>
  );
}
